baseURL: https://algernon.rhahi.com/
languageCode: en-us
title: Algernon ðŸŒ¼
description: A journal of learning
theme: no-style-please
taxonomies:
  tag: tags
  series: series
params:
  theme_config:
    appearance: dark
